WIP: Feature/Campaign API integration
PLATAHUB/clevertap-ruby pull request #1
Opened 2020-10-07 20:19 UTC by brayvasq

## :loudspeaker: Tipo de cambio
- [x] Nueva característica

## :scroll: Descripción

- Se añade el modelo que permite construir el cuerpo a enviar en las peticiones

## Qué falta?
- Servicio que permita conectarse a la api de campaigns de CleverTap.
- Añadir opcion de crear campañas al modelo `CleverTap`.

## :green_heart: ¿Cómo se hicieron pruebas?
Se añaden pruebas unitarias.

2020-10-09 04:24 UTC, 2xG commented on lib/clever_tap/campaign.rb
> +  class NoUsersError < RuntimeError
**suggestion**: renombrar a `NoReceiversError` o `NoAddresseesError`

Esas palabras describen mejor la calidad de receptor del usuario en este caso.

2020-10-09 04:24 UTC, 2xG commented on lib/clever_tap/campaign.rb
> +    def initialize(**args)
**suggestion**: usar "Keyword arguments"

Creo que seria mejor apuntar nuestro desarrollo a Ruby 2.0+, y para nosotros vamos a manejar la rama `ruby_2.0.0_support` por separado.
https://thoughtbot.com/blog/ruby-2-keyword-arguments

2020-10-09 04:24 UTC, 2xG commented on lib/clever_tap/campaign.rb
> +      put_to_pair
**suggestion**: renombrar `put_..._pair` => `..._hash`

2020-10-09 04:24 UTC, 2xG commented on README.md
> +campaign = CleverTap::Campaign.new(
**nitpick**: usar sintaxis de `CleverTap::Campaign.new \`

porque si, podemos =)

2020-10-09 04:24 UTC, 2xG commented on lib/clever_tap/campaign.rb
> +      put_to_pair
Note que sigues el patron de `CleverTap::Entity` hmmmmm
no me gusta este `put_..._pair`

2020-10-09 04:24 UTC, 2xG commented on spec/units/campaign_spec.rb
> +      {
**suggestion**: hacerlo mas compacto

```ruby
{ to: {
    'Email' => ['example@email.com'],
    'FBID' => ['fbidexample']
  },
  tag_group: 'mytaggroup',
  respect_frequency_caps: false,
  content: { 'body' => 'Smsbody' }
}
```

2020-10-09 04:24 UTC, 2xG commented on lib/clever_tap/creator.rb
> +    CAMPAIGNS_NOTIFICATIONS_NAMES = {
**suggestion**: renombrar `CAMPAIGNS_NOTIFICATIONS_NAMES` => `CAMPAIGNS_NOTIFICATIONS_ENDPOINTS`

2020-10-09 04:24 UTC, 2xG commented on lib/clever_tap/campaign.rb
> +
**issue**: agregar `MAX_USERS_PER_CAMPAIGN = 1000`

y crear validacion de cantidad de receptores.

> The to parameter is an object that has the following child properties: FBID, Email, Identity, objectId, which are used as identifiers to target your users. Each request can contain a max of 1000 users across these identifiers.

2020-10-09 04:24 UTC, 2xG commented on lib/clever_tap/creator.rb
> +    def parse_response(http_response)
**thought**: aqui podemos pensar en el formato que nos puede servir en nuestro app

2020-10-09 05:27 UTC, 2xG commented on lib/clever_tap/campaign.rb
> +      indentities.all? { |identity| ALLOWED_IDENTITIES.include?(identity.to_s) }
**suggestion**: encontré una forma elegante para hacer esta prueba

```ruby
(indentities - ALLOWED_IDENTITIES).empty?
```

2020-10-09 05:28 UTC, 2xG commented on README.md
> +campaign = CleverTap::Campaign.new(
ay caramba es un ejemplo no mas *facepalm.jpg*

2020-10-09 06:12 UTC, 2xG commented on README.md
> +client.create_campaign(campaign)
**issue**: falta el metodo `create` para `CleverTap:: Client`

es lo que usamos en civico-main https://github.com/PLATAHUB/Civico/blob/prod-civico2-new/config/initializers/clevertap.rb. Y por la existencia de dos aplicaciones de CT que usamos al mismo tiempo no podemos usar la instancia de `CleverTap` y toca configurar dos clientes independientes.

2020-10-09 22:07 UTC, brayvasq commented on lib/clever_tap/campaign.rb
> +      put_to_pair
@2xG no le gusta el nombre de los métodos o la manera en la que se hace el proceso?

2020-10-13 20:45 UTC, brayvasq commented on lib/clever_tap/creator.rb
> +    def parse_response(http_response)
@2xG Colocar un yield?

2020-10-13 20:47 UTC, brayvasq commented on lib/clever_tap/campaign.rb
> +    def to_hash
@2xG Este nombre no generaría confusión?

2020-10-15 05:54 UTC, 2xG commented on README.md
> +      'deep_link' => 'https://www.google.com',
**nitpick**: para safari - https://apple.com :smile:

2020-10-15 05:54 UTC, 2xG commented on README.md
> +      'deep_link' => 'http://www.example.com',
**nitpick**: para chrome - https://google.com :point_left:

2020-10-15 05:54 UTC, 2xG commented on README.md
> +      'deep_link' => 'https://www.google.com',
**nitpick**: para firefox - https://mozilla.org :fire: :fox_face:

2020-10-15 05:54 UTC, 2xG commented on README.md
> +```ruby
**suggestion**: agregar link to CT docs

https://developer.clevertap.com/docs/create-campaign-api

2020-10-15 05:54 UTC, 2xG commented on lib/clever_tap/campaign.rb
> +  class LimitExceededError < RuntimeError
**suggestion**: renombrar `LimitExceededError` -> `ReceiversLimitExceededError`

2020-10-15 05:54 UTC, 2xG commented on lib/clever_tap/campaign.rb
> +    def initialize(to: nil,
**question**: todos los campos son obligatorios?

2020-10-15 05:54 UTC, 2xG commented on lib/clever_tap/campaign.rb
> +    def to_hash
**suggestion**: `receivers_hash`

2020-10-15 05:54 UTC, 2xG commented on lib/clever_tap/creator.rb
> +  class Creator
**suggestion**: `CampaignCreator`

2020-10-15 05:54 UTC, 2xG commented on lib/clever_tap/creator.rb
> +    def parse_response(http_response)
podemos pensarlo en el momento de utilizar en el app, por ahora dejemoslo asi

2020-10-15 16:17 UTC, brayvasq commented on lib/clever_tap/campaign.rb
> +    def initialize(to: nil,
@2xG Solamente to: y content:

2020-10-15 17:37 UTC, 2xG requested changes

2020-10-15 17:37 UTC, 2xG commented on lib/clever_tap/campaign.rb
> +    def initialize(to: nil,
**chore**: entonces debe ser asi
```ruby
def initialize(to: , content: , tag_group: nil,
                    ...,
                    platform_specific: nil)
```

2020-10-27 08:25 UTC, merged