change: Split campaign types into classes
PLATAHUB/clevertap-ruby pull request #3
Opened 2020-10-16 19:01 UTC by brayvasq

## :loudspeaker: Change type
- [x] Refactoring

## :scroll: Description

- [x] Add classes for each type of Campaingn (sms, web_push, push, email).

## :green_heart: Testing
Specs

2020-10-22 07:25 UTC, 2xG requested changes

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap.rb
> +require 'clever_tap/sms_campaign'
**suggestion**: `clever_tap/campaign/sms` etc

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap/campaign.rb
>      def content_hash
**suggestion**:
```ruby
raise NotImplementedError
```
aqui y en otros lugares agregar este tipo de errores que no permiten usar la clase `Campaign` directamente.

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap/campaign_creator.rb
> +    def initialize(record)
**suggestion**: `record` -> `campaign`

**thought**: campaign tiene mas sentido que record, record es mas como entidad de DB

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap/campaign_creator.rb
> +    def campaign_type(record)
**suggestion**: `campaign_type(record)` -> `type_of(campaign)`

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap/campaign_creator.rb
> +      end
**chore**: agregar `else`

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap/campaign.rb
> +    def platform_specific_hash; end
**question**: tiene sentido tenerlo aqui?

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap/campaign.rb
>      def content_platform_specific
**question**: que proposito tiene?

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap.rb
> +require 'clever_tap/sms_campaign'
**suggestion**:  `CleverTap::EmailCampaign` -> `CleverTap::Campaign::Email`

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap.rb
> +  def create_campaign(campaign)
**thought**: parece que los métodos de la clase `CleverTap` como tal están planeados para morir

Desde README.md
> Available in v0.2.0 but will be depricated as of v1.0.0 `.upload_event` accepts as a first argument an object responding to `#to_h` and `#[]` and a second parameter keyword argument `name: <name>`.

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap/campaign_creator.rb
> +    def initialize(record)
veo que en `Uploader.initialize` manejan `records`, pero los perfiles y eventos parecen records =)

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap/client.rb
> +    def obtain_receivers(campaign)
**suggestion**: simplificar la logica: transformar el hash `campaign.to` a un array de pares `[id_type, id]`:

```ruby
identitiy_pairs = campaign.to.map { |type, list| list.map { |id| [type, id] } }
                          .flatten(1)
pp identitiy_pairs
```

en esta etapa tenemos algo asi en la salida

``` ruby
[
    ["FBID", "102029292929388"],
    ["FBID", "114342342453463"],
    ["GPID", "1928288389299292"],
    ["Email", "john@doe.com"],
    ["Email", "jane@doe.com"],
    ["Identity", "JohnDoe"],
    ["objectId", "_asdnkansdjknaskdjnasjkndja"],
    ["objectId", "-adffajjdfoaiaefiohnefwprjf"]
]

```

después cortarlo en pedazos de 1000 ids y volver a armar los hashes de estos pedazos:

```ruby
identitiy_pairs.each_slice(Campaign::MAX_USERS_PER_CAMPAIGN) do |slice|
  chunked_to =  slice.group_by(&:first)
                     .map { |k, v| [k, v.map(&:last)] }
                     .to_h
  pp chunked_to
end
```

aquí dentro del bloque `each_slice` podemos crear nuevas campañas con `to = chunked_to` y enviarlas.
en el ejemplo de arriba, asumiendo `Campaign::MAX_USERS_PER_CAMPAIGN = 2` en la consola tengo:

```ruby
{"FBID"=>["102029292929388", "114342342453463"]}
{"GPID"=>["1928288389299292"], "Email"=>["john@doe.com"]}
{"Email"=>["jane@doe.com"], "Identity"=>["JohnDoe"]}
{"objectId"=>["_asdnkansdjknaskdjnasjkndja", "-adffajjdfoaiaefiohnefwprjf"]}
```

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap/client.rb
> +    def obtain_receivers(campaign)
me llego la idea que puedes poner `yield chunked_to` dentro del bloque `each_slice` y dentro del método `create_campaign` pasar el bloque (y cambiar el nombre del metodo `obtain_receivers` -> `receivers_chunks`
```ruby
def create_campaign(campaign)
  responses = []

  receivers_chunks(campaign) do |receivers|
    campaign.to = receivers
    responses << CampaignCreator.new(campaign).call(self)
  end

  responses
end
```

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap/client.rb
> +      if campaign.receivers_limit_exceeded?
**suggestion**: moverlo al metodo `obtain_receivers`

```ruby
def obtain_receivers(campaign)
  return [campaign.to] unless campaign.receivers_limit_exceeded?
...
end
```
y dejar un solo método de crear campañas `create_campaign` pero de manera `bulk_create_campaign`. es decir si no son mas de 1000 identificadores devolvemos la lista de manera unificada: array con un solo elemento

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap/email_campaign.rb
> +  class EmailCampaign < Campaign
**suggestion**: `class Campaign::Email`

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap/push_campaign.rb
> +  class PushCampaign < Campaign
**suggestion**: `class Campaign::Push`

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap/push_campaign.rb
> +      android = @platform_specific[:android] || @platform_specific['android']
**suggestion**: creo que puedes usar `symbolize_keys` o `symbolize_keys!` dentro del `initialize` para simplificar estos condiciones aqui y en otros lgares

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap/sms_campaign.rb
> +  class SmsCampaign < Campaign
**suggestion**: `class Campaign::Sms`

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap/web_push_campaign.rb
> +  class WebPushCampaign < Campaign
**suggestion**: `class Campaign::WebPush`

2020-10-22 07:25 UTC, 2xG commented on lib/clever_tap/campaign.rb
> +      raise ReceiversLimitExceededError if receivers_limit_exceeded?
**praise**: :+1: se ve mas limpio

2020-10-22 15:49 UTC, brayvasq commented on lib/clever_tap/campaign.rb
>      def content_platform_specific
Se puede quitar. Realmente se está validando ese hash en las clases WebPush y Push, ya que al final eso va en el content de esas dos clases.

Lo había dejado ahí por que en la documentación aparecía como un parámetro independiente y no dentro de content.

2020-10-22 19:01 UTC, brayvasq commented on lib/clever_tap/push_campaign.rb
> +      android = @platform_specific[:android] || @platform_specific['android']
@2xG Creo que ese es un método de rails, no de ruby en sí.

2020-10-22 20:57 UTC, 2xG requested changes

2020-10-22 20:57 UTC, 2xG commented on lib/clever_tap/client.rb
> +      return [CampaignCreator.new(campaign).call(self)] unless campaign.receivers_limit_exceeded?
perdon creo que no explique bien.
la idea fue de meter esto en `receivers_chunks` para evitar el uso doble de `CampaignCreator.new(campaign).call(self)`, pero como se cambio la idea como usar este método eso debería ser así
```ruby
def receivers_chunks(campaign)
  chunked_to = campaign.to unless campaign.receivers_limit_exceeded?
  ...
end
```
me hago entender?

2020-10-23 04:05 UTC, 2xG commented on lib/clever_tap/campaign.rb
> +      raise NoReceiversError if empty_receivers?
**praise**: :+1:

2020-10-23 04:05 UTC, 2xG commented on lib/clever_tap/campaign.rb
> +      raise ReceiversLimitExceededError if receivers_limit_exceeded?
**praise**: :+1:

2020-10-23 14:22 UTC, brayvasq commented on lib/clever_tap/client.rb
> +      return [CampaignCreator.new(campaign).call(self)] unless campaign.receivers_limit_exceeded?
No, no entiendo. En ese caso se necesitaría otro yield?

2020-10-23 21:18 UTC, 2xG commented on lib/clever_tap/client.rb
> +      identity_pairs = campaign.to.flat_map { |type, list| list.map { |id| [type, id] } }
**praise**: no sabia que existe `flat_map` :smiley:

2020-10-23 21:23 UTC, merged